[package]
name = "nes_web"
version = "0.1.0"
authors = ["Ryan Norris <rynorris@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nes = { path = "../nes" }
wasm-bindgen = "0.2"

